name: http_mock_adapter
description: HTTP mock adapter for Dio & Mockito. By simply defining requests
  and corresponding responses through predefined adapters, you will be able to
  mock requests sent via Dio.
version: 0.3.0
homepage: https://lomsa.com
repository: https://github.com/lomsa-dev/http-mock-adapter
issue_tracker: https://github.com/lomsa-dev/http-mock-adapter/issues

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  dio: ^4.0.0
  mockito: ^5.0.3

dev_dependencies:
  lints: ^1.0.1
  test: ^1.16.8
