name: http_mock_adapter
description: A simple to use mocking package for Dio intended to be used in tests. It provides various types and methods to declaratively mock request-response communication.
version: 0.6.0
homepage: https://github.com/lomsa-dev/http-mock-adapter
repository: https://github.com/lomsa-dev/http-mock-adapter
issue_tracker: https://github.com/lomsa-dev/http-mock-adapter/issues

environment:
  sdk: '^3.0.0'

dependencies:
  collection: ^1.17.1
  dio: ^5.3.2
  http_parser: ^4.0.2
  logger: ^2.0.1

dev_dependencies:
  lints: '>=2.1.1'
  test: ^1.24.6
  fake_async: ^1.3.1
