name: http_mock_adapter
description: A simple to use mocking package for Dio intended to be used in tests. It provides various types and methods to declaratively mock request-response communication.
version: 0.3.0
homepage: https://lomsa.com
repository: https://github.com/lomsa-dev/http-mock-adapter
issue_tracker: https://github.com/lomsa-dev/http-mock-adapter/issues

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  collection: ^1.15.0
  dio: ^4.0.0
  http_parser: ^4.0.0

dev_dependencies:
  lints: ^1.0.1
  test: ^1.16.8
